micronaut:
  application:
    name: micronautApi
datasources:
  default:
    url: jdbc:postgresql://192.168.100.12:15432/micronaut
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'root'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

